[package]
name = "renderer"
version = "0.1.0"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]

[dependencies]
orbclient = "*"
orbimage = { git = "https://github.com/redox-os/orbimage.git" }
